# Secret key
jwt:
  secretKey: skjdoijiufkdjnkjnekjnfjekjsdfknwkj983fjcnxsnmwlhv0408yvfhjvwp385792infnvoefoiu3uwfihvi3wry


spring:
  application:
    name: api-gateway

# API Gateway Configs
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrdersFilter
            - name: AuthenticationFilter
              args:
                isEnabled: false
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
              args:
                isEnabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# BCZ Getting WIPERS-20PLH00.mshome.net as Host-name
  instance:
    hostname: localhost
    prefer-ip-address: true
