# To Show Circuit Breaker Health-checks on Actuator
management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always

resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxRetryAttempts: 3
        waitDuration: 100ms
  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 1s
        limitForPeriod: 100
        timeoutDuration: 10ms
  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 10
        failureRateThreshold: 20
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10




